/** COUNTER app tables use the bij_ prefix (shared database). */
export const T = {
  appUser: "bij_app_user",
  products: "bij_products",
  productVariants: "bij_product_variants",
  purchases: "bij_purchases",
  purchaseItems: "bij_purchase_items",
  sales: "bij_sales",
  saleItems: "bij_sale_items",
  stockAdjustments: "bij_stock_adjustments",
  inventoryLedger: "bij_inventory_ledger",
  settings: "bij_settings",
  parties: "bij_parties",
  partyLedger: "bij_party_ledger",
  payments: "bij_payments",
  expenseCategories: "bij_expense_categories",
  expenses: "bij_expenses",
  investments: "bij_investments",
  productCategories: "bij_product_categories",
  salePaymentMethods: "bij_sale_payment_methods",
  accounts: "bij_accounts",
  accountLedger: "bij_account_ledger",
  investmentAllocations: "bij_investment_allocations",
} as const;
